/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.CarroDao;
import dao.CorDao;
import dao.ModeloDao;
import entidade.Carro;
import entidade.Cor;
import entidade.Modelo;
import javax.swing.JOptionPane;

/**
 *
 * @author vini
 */
public class TelaCadCarro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadCarro
     */
    public TelaCadCarro() {
        initComponents();
        
        ModeloDao dao = new ModeloDao();
        
        for(Modelo m : dao.lista()){
            
            jCmodelo.addItem(m);
        }
        
        CorDao cordao = new CorDao();
        
        for(Cor c : cordao.lista()){
            
            jCcor.addItem(c);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCmodelo = new javax.swing.JComboBox<>();
        jCcor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTano = new javax.swing.JTextField();
        jTaluguel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFplaca = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("CADASTRO DE CARROS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jCmodelo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jCmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Modelo:" }));
        jCmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmodeloActionPerformed(evt);
            }
        });
        getContentPane().add(jCmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, -1));

        jCcor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jCcor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Cor:" }));
        jCcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcorActionPerformed(evt);
            }
        });
        getContentPane().add(jCcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Ano de Fabricação:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Placa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Valor do Aluguel:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(jTano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        jTaluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaluguelActionPerformed(evt);
            }
        });
        getContentPane().add(jTaluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 60));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 180, 60));

        try {
            jFplaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU#U##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFplaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jFplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3024.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTaluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaluguelActionPerformed

    private void jCmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmodeloActionPerformed

    private void jCcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salvarCarro();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     TelaPrincipal telap = new TelaPrincipal();
     telap.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Object> jCcor;
    private javax.swing.JComboBox<Object> jCmodelo;
    private javax.swing.JFormattedTextField jFplaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTaluguel;
    private javax.swing.JTextField jTano;
    // End of variables declaration//GEN-END:variables

    private void salvarCarro(){
        Carro car = new Carro();
        car.setAno(Integer.parseInt(String.valueOf(jTano.getText())));
        car.setPlaca(jFplaca.getText());
        car.setValorAluguel(Integer.parseInt(String.valueOf(jTaluguel.getText())));
        Modelo mod = new Modelo();
        mod = (Modelo) jCmodelo.getSelectedItem();
        car.setModelo(mod);
        Cor cor = new Cor();
        cor = (Cor) jCcor.getSelectedItem();
        car.setCor(cor);
        
        try {
            new CarroDao().salvar(car);
            JOptionPane.showMessageDialog(this,"Salvo com sucesso");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Erro ao Salvar "+ex.getMessage());
            
        }
        
        
    }

}
